spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/mydbs_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

jwt.secret=TXlEQlMtU3VwZXItU2VjdXJlLUtleS1Gb3ItSFM1MTItQXV0aC1Nb2R1bGUtMjAyNi1NeURCUy1CYWNrZW5kLVNlcnZlci1LZXk=
jwt.expiration=86400000

app.bootstrap.admin.email=admin@mydbs.com
app.bootstrap.admin.password=Admin@123456
app.bootstrap.admin.first-name=Super
app.bootstrap.admin.last-name=Admin
app.bootstrap.admin.user-code=ADM-0001
app.bootstrap.admin.phone-number=070000000